services:
  nginx:
    image: nginx:1.27.5-alpine3.21
    ports:
      - "80:80"
    volumes:
      - ./nginx.template.conf:/etc/nginx/templates/default.conf.template:ro
    environment:
      - API_PORT=${API_PORT}
    depends_on:
      - api
    networks:
      - tfidf-network

  api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - tfidf-network
    volumes:
      - uploads-data:/uploads
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.21
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tfidf-network

networks:
  tfidf-network:
    driver: bridge

volumes:
  pgdata:
  uploads-data: